services:

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  tests:
    build: .
    depends_on:
      - api
    environment:
      BASE_URL: http://api:8000
    volumes:
      - ./reports:/app/reports
    command: pytest -v --html=reports/report.html --self-contained-html